---
- name: Collect facts
  hosts: all
  become: true
  gather_facts: smart
  tasks:
    - debug: msg="Fetching facts from cluster instances"
      tags: [print_action]
    - setup:

- name: Create groups
  hosts: localhost
  gather_facts: false
  vars:
    bc_private_interface: enp0s8
  tasks:
    - debug: msg="Calculate"
      tags: [print_action]
    - name: "Add boot node to group bcboot"
      tags:
        - always
      add_host:
        name: "{{ item }}"
        groups: bcboot
        inventory_dir: "{{ hostvars[item].inventory_dir }}"
      loop: "{{ groups['all'] }}"
      when: '"boot" in hostvars[item]["ansible_hostname"]'
    - name: "Add all nodes to group bcpeers"
      tags:
        - always
      add_host:
        name: "{{ item }}"
        groups: bcpeers
        inventory_dir: "{{ hostvars[item].inventory_dir }}"
      loop: "{{ groups['all'] }}"
      when: '"prod" in hostvars[item]["ansible_hostname"] or "boot" in hostvars[item]["ansible_hostname"]'
    - name: "Add monitnoring nodes to group monitoring_peer"
      tags:
        - always
      register: _create_group_monitoring
      add_host:
        name: "{{ item }}"
        groups: monitoring_peer
        inventory_dir: "{{ hostvars[item].inventory_dir }}"
      loop: "{{ groups['all'] }}"
      when: '"monitoring" in hostvars[item]["ansible_hostname"]'
    - name: "Add all nodes to group allnodes"
      tags:
        - always
      add_host:
        name: "{{ item }}"
        groups: allnodes
        inventory_dir: "{{ hostvars[item].inventory_dir }}"
      loop: "{{ groups['all'] }}"
      when: '"prod" in hostvars[item]["ansible_hostname"] or "boot" in hostvars[item]["ansible_hostname"] or "full" in hostvars[item]["ansible_hostname"]'

- name: Converge boot node
  hosts: "*boot*"
  become: true
  vars:
    bc_polkadot_comp_state_boot: present
    bc_polkadot_comp_state_bench: present
    bc_polkadot_bench_shard_id: "{{ play_hosts.index(inventory_hostname) | int }}"
    bc_polkadot_bench_shards: "{{ play_hosts | length }}"
    install_promstack: true
  roles:
    - role: azavea.ansible-pip
    - role: tank.ansible-polkadot

- name: Converge validator node
  hosts: "*prod*"
  become: true
  vars:
    bc_polkadot_comp_state_prod: present
    bc_polkadot_comp_state_bench: present
    install_promstack: true
    bc_polkadot_extra_validator_id: "{{ play_hosts.index(inventory_hostname) | int }}"
    bc_polkadot_bench_shard_id: "{{ play_hosts.index(inventory_hostname) | int }}"
    bc_polkadot_bench_shards: "{{ play_hosts | length }}"
  roles:
    - role: azavea.ansible-pip
    - role: tank.ansible-polkadot

- name: Converge monitoring node
  hosts: "*monitoring*"
  become: true
  vars:
    bc_comp_state_monitoring: present
    install_promstack: true
    admin_user: tank
    admin_password: tank
    grafana_http_port: 80
  roles:
    - role: azavea.ansible-pip
    - role: tank.ansible-polkadot
